### ISSUE TITLE
Overlapping Bases info missing in the report

### ISSUE THREAD

**Issue by berguner** [heathsc/gemBS#18]
Hello,

With the 2.0 release the `Overlapping Bases` info is removed from the mapping report. Can you please check this issue?

Best,
Bekir

**Comment by MarcosFernandez** [comment]
Hi Bekir,

This field has been moved to the Alignments and Coverage report generated during the calling process.

We moved it there because from the mapping stats we can just get and approximate value, while from the processing of the alignments (bscall) we can extract the actual value.

Cheers,
Marcos.

**Comment by berguner** [comment]
Thank you Marcos for the explanation.
Cheers,
Bekir
