### ISSUE TITLE
What is a dbSNP_index?

### ISSUE THREAD

**Issue by IsmailM** [heathsc/gemBS#30]
Hi, 

I'm trying to create a dbSNP index file:

I have the following in my config file:

```
reference = /home/ucbtmog/d/wgbs/reference/hg38.fa.gz
dbSNP_dir = /home/ucbtmog/d/wgbs/reference/dbsnp
dbSNP_files = ${dbSNP_dir}/*.bed.gz
```

However, when I run `gemBS index -t 80`, I get the following:

```
Bisulphite Index /home/ucbtmog/a/75/EGAZ00001016575/ref_indexes/hg38.BS.gem already exists, skipping indexing
The dbSNP Index file must be specified using the configuration parameter dbSNP_index.

```

As such, what is the `dbSNP_index`? Is this a tabix index?

**Comment by heathsc** [comment]
dbSNP_index is a custom index generated by gemBS that contains the positions and names of the SNPs extracted from the dbSNP bed files.  If you give a path to the dbSNP_index file, it will be created if it does not already exist.  Note that the dbSNP index is not required for normal operation of gemBS, but is required for annotation of SNP names in the VCF file.

**Comment by IsmailM** [comment]
Thanks for the explanation - might be useful to add this to the docs.

Would also be nice to have a default value for this...

**Comment by heathsc** [comment]
There is a section in the manual on the dbSNP_index - if you have any suggestions about how this could be made clearer please let me know!  I have added a default value for dbSNP_index if dbSNP_files and index_dir are both set (index_dir/dbSNP_gemBS.idx)

The message from gemBS prepare about the missing index file is simple informational rather than a warning of any problem.  It is to tell the user that they should run gemBS index to create the missing indices (or correct the configuration file if the indices do exist but gemBS has not found them).   I have added a message when missing files have been found to say that gemBS index should be run to generate the missing files.

**Comment by minghao4** [comment]
Hello,

The default value doesn't seem to be working. I have `index_dir` set in the configuration file and here's what I have tried:
- Various spelling combinations of dbsnp_index in the configuration file (dbsnp_index, dbsnp_idx, dbSNP_index, dbSNP_idx)
- Setting dbsnp_files in the configuration file (dbsnp_files, dbSNP_files)
- Using the -d flag in gemBS index to try and set the dbsnp files.

This seems to be going on with both the version from bioconda and building from the source files here.
