### ISSUE TITLE
Mapping requires high memory

### ISSUE THREAD

**Issue by berguner** [heathsc/gemBS#4]
Hello,

I have realized that `gemBS mapping` command requires quite a lot of memory. A far as I can understand gem-mapper requires about 20GB of memory for human genome. However, total memory footprint  of `gemBS mapping` increases depending on the size of the input fastq file. I suppose it is because `gem-mapper & readNameClean & bamView & bamSort` commands are piped with python `subprocess.PIPE` and this is causing the sorting to be done in-memory. Is there a workaround to overcome this issue?

Best,
Bekir

**Comment by MarcosFernandez** [comment]
Hi Bekir,

Thanks a lot for your report.  The memory footprint is affected by the number of threads used and the `samtools sort` buffer size.

Reducing the number of threads used by `gemBS mapping` can help on the memory used, but the total performing time will be higher. You can play with this parameter if the memory footprint is a problem for you.

Understanding your problem, we will add a new parameter for the `gemBS mapping` in order to configure the sorting buffer size used by `samtools sort` (`-m INT`). We will do it for the next release.

The sorting process is not completely done in main memory. It uses partial files on disk, stored at a temporary folder, to have chunks of already sorted reads which are finally merged.

Cheers,
Marcos.
