### ISSUE TITLE
gemBS bsMap-report ZeroDivisionError: float division by zero 

### ISSUE THREAD

**Issue by IsmailM** [heathsc/gemBS#9]
When running with **single-end reads**:

```bash
gemBS bsMap-report -j "pgp2/gembs.json" -i "pgp2/gembs_mapping1" -n "pgp2" -o "out"
```
I get the following error: 

```bash
------------ Input Parameter ------------
Input File(s)    : None
Output File(s)   : None
Output Directory : /mnt/254b78b9-76b4-422d-84b1-cc632bff60f7/IsmailM/wgbs/PGP2/gembs_mapping1/report
TMP Directory    : /tmp/
Threads          : 1

------- Mapping Report ----------
Name            : ANALYSIS_PGP2_1

Building html reports...
Traceback (most recent call last):
  File "/home/ucbtmog/.local/bin/gemBS", line 9, in <module>
    load_entry_point('gemBS==1.7', 'console_scripts', 'gemBS')()
  File "/home/ucbtmog/.local/lib/python2.7/site-packages/src/commands.py", line 54, in gemBS
    instances[args.command].run(args)
  File "/home/ucbtmog/.local/lib/python2.7/site-packages/src/production.py", line 836, in run
    report.buildReport(inputs=self.sample_lane_files,output_dir=self.output_dir,name=self.name)
  File "/home/ucbtmog/.local/lib/python2.7/site-packages/src/report.py", line 925, in buildReport
    vector_samples.append(SampleStats(name=sample,list_lane_stats=list_stats_lanes))
  File "/home/ucbtmog/.local/lib/python2.7/site-packages/src/reportStats.py", line 563, in __init__
    self.averageSampleOverlappedBases = (float(self.totalSampleOverlappedBases)/float(self.totalSampleBases)) * 100
ZeroDivisionError: float division by zero
```

The same command works with **paired end reads**...

The issue is on the last line (L563) of the snippet below:

https://github.com/heathsc/gemBS/blob/c7db033c59c42a3ed3c4dd53a1212471db8b3635/src/reportStats.py#L545-L564

Adding simple print messages here shows: 
```
self.totalSampleOverlappedBases = 0.0
self.totalSampleBases = 0.0
```

If I replace this line with the following, the report is generated:

```python
        self.averageSampleOverlappedBases = 1
```

So I think an `if` statement is needed here so that this isn't run with single end reads?
i.e. something like:

```python
if self.is_paired:
  self.averageSampleOverlappedBases = (float(self.totalSampleOverlappedBases)/float(self.totalSampleBases)) * 100
```

**Comment by MarcosFernandez** [comment]
Hi Ismail,

Thanks a lot for reporting this issue. It has been already updated and committed to the repository.

Cheers,
Marcos.

**Comment by IsmailM** [comment]
Hey @MarcosFernandez,

The updated section needs to be moved down after where `is_paired` is checked and updated (i.e. after L570):

https://github.com/heathsc/gemBS/blob/19296b38001aab848e690ccd4a6ed7c7e9556bf1/src/reportStats.py#L563-L571

Just retested the latest version, and it simply fails with the aforementioned bug. Moving it after L570 fully fixes this issue. 👍 

Ismail

**Comment by MarcosFernandez** [comment]
Thanks Ismail,


That would be fixed in comming version of GEMBS.


Cheers,

Marcos.


________________________________
De: Ismail Moghul <notifications@github.com>
Enviado: luns, 26 de febreiro de 2018 1:40
Para: heathsc/gemBS
CC: MARCOS FERNANDEZ CALLEJO; Mention
Asunto: Re: [heathsc/gemBS] gemBS bsMap-report ZeroDivisionError: float division by zero (#9)


Hey @MarcosFernandez<https://github.com/marcosfernandez>,

The updated section needs to be moved down after where is_paired is checked and updated (i.e. after L570):

https://github.com/heathsc/gemBS/blob/19296b38001aab848e690ccd4a6ed7c7e9556bf1/src/reportStats.py#L563-L571

Just retested the latest version, and it simply fails with the aforementioned bug. Moving it after L570 fully fixes this issue. ??

Ismail

-
